# Usa uma imagem base do Ubuntu
FROM ubuntu:20.04

# Atualiza os pacotes e instala dependências
RUN apt-get update && apt-get install -y \
    tor \
    git \
    sudo \
    curl \
    bash \
    && rm -rf /var/lib/apt/lists/*

# Clona o repositório Insta-Cypher
RUN git clone https://github.com/pralinkhaira/Insta-Cypher /insta-cypher

# Define o diretório de trabalho
WORKDIR /insta-cypher

# Torna o script executável
RUN chmod +x insta.sh

# Expondo a porta 9050 para o Tor
EXPOSE 9050

# Inicializa o Tor diretamente e executa o script
CMD tor & ./insta.sh

